// Code generated by "stringer -type=ATCmd -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdModel-0]
	_ = x[CmdName-1]
	_ = x[CmdSn-2]
	_ = x[CmdReboot-3]
	_ = x[CmdRestore-4]
	_ = x[CmdVer-5]
	_ = x[CmdMac-6]
	_ = x[CmdLora-7]
	_ = x[CmdWan-8]
	_ = x[CmdLPort-9]
	_ = x[CmdSock-10]
	_ = x[CmdLinkSta-11]
	_ = x[CmdUartClr-12]
	_ = x[CmdRegMod-13]
	_ = x[CmdRegInfo-14]
	_ = x[CmdHeartMod-15]
	_ = x[CmdHeartInfo-16]
	_ = x[CmdShortM-17]
	_ = x[CmdTmoRst-18]
	_ = x[CmdTmoLink-19]
	_ = x[CmdWebCfgPort-20]
	_ = x[CmdModWkMod-21]
	_ = x[CmdModPtcl-22]
	_ = x[CmdModGtwyTm-23]
	_ = x[CmdModCmdEdit-24]
	_ = x[CmdHtpReqMode-25]
	_ = x[CmdHtpUrl-26]
	_ = x[CmdHtpHead-27]
	_ = x[CmdMqttCloud-28]
	_ = x[CmdMqtKpAlive-29]
	_ = x[CmdMqtDevId-30]
	_ = x[CmdMqtUser-31]
	_ = x[CmdMqtPass-32]
	_ = x[CmdMqtPrdKey-33]
	_ = x[CmdMqtSub-34]
	_ = x[CmdMqtPub-35]
}

const _ATCmd_name = "MODELNAMESNREBTRESTOREVERMACLORAWANLPORTSOCKLINKSTAUARTCLRREGMODREGINFOHEARTMODHEARTINFOSHORTMTMORSTTMOLINKWEBCFGPORTMODWKMODMODPTCLMODGTWYTMMODCMDEDITHTPREQMODEHTPURLHTPHEADMQTTCLOUDMQTKPALIVEMQTDEVIDMQTUSERMQTPASSMQTTPRDKEYMQTSUBMQTPUB"

var _ATCmd_index = [...]uint8{0, 5, 9, 11, 15, 22, 25, 28, 32, 35, 40, 44, 51, 58, 64, 71, 79, 88, 94, 100, 107, 117, 125, 132, 141, 151, 161, 167, 174, 183, 193, 201, 208, 215, 225, 231, 237}

func (i ATCmd) String() string {
	if i < 0 || i >= ATCmd(len(_ATCmd_index)-1) {
		return "ATCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ATCmd_name[_ATCmd_index[i]:_ATCmd_index[i+1]]
}
