// Code generated by "stringer -type=ATCommand -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMD_MODEL-0]
	_ = x[CMD_NAME-1]
	_ = x[CMD_SN-2]
	_ = x[CMD_REBT-3]
	_ = x[CMD_RESTORE-4]
	_ = x[CMD_VER-5]
	_ = x[CMD_MAC-6]
	_ = x[CMD_LORA-7]
	_ = x[CMD_WAN-8]
	_ = x[CMD_LPORT-9]
	_ = x[CMD_SOCK-10]
	_ = x[CMD_LINKSTA-11]
	_ = x[CMD_UARTCLR-12]
	_ = x[CMD_REGMOD-13]
	_ = x[CMD_REGINFO-14]
	_ = x[CMD_HEARTMOD-15]
	_ = x[CMD_HEARTINFO-16]
	_ = x[CMD_SHORTM-17]
	_ = x[CMD_TMORST-18]
	_ = x[CMD_TMOLINK-19]
	_ = x[CMD_WEBCFGPORT-20]
	_ = x[CMD_MODWKMOD-21]
	_ = x[CMD_MODPTCL-22]
	_ = x[CMD_MODGTWYTM-23]
	_ = x[CMD_MODCMDEDIT-24]
	_ = x[CMD_HTPREQMODE-25]
	_ = x[CMD_HTPURL-26]
	_ = x[CMD_HTPHEAD-27]
	_ = x[CMD_MQTTCLOUD-28]
	_ = x[CMD_MQTKPALIVE-29]
	_ = x[CMD_MQTDEVID-30]
	_ = x[CMD_MQTUSER-31]
	_ = x[CMD_MQTPASS-32]
	_ = x[CMD_MQTTPRDKEY-33]
	_ = x[CMD_MQTSUB-34]
	_ = x[CMD_MQTPUB-35]
}

const _ATCommand_name = "MODEL, Query modelNAME, Query/Set NameSN, Query/Set IDREBT, Reboot deviceRESTORE, Factory resetVER, Query version informationMAC, Querying the MAC addressLORA, Query/set the wireless parameters of the machineWAN, Query/set network parametersLPORT, Query/set the local port numberSOCK, Query/set the working mode of the machine and network parameters of the target deviceLINKSTA, Query network link statusUARTCLR, Query/set serial port cache clearing statusREGMOD, Query/Set Registration Package ModeREGINFO, Query/set custom registration package contentHEARTMOD, Query/set the heartbeat packet modeHEARTINFO, Query/Set Heartbeat DataSHORTM, Query/Set Short Connection TimeTMORST, Query/set timeout restart timeTMOLINK, Query/set the time and times of disconnection and reconnectionWEBCFGPORT, Web configuration portMODWKMOD, Query Modbus working mode and command timeout timeMODPTCL, Enable Modbus TCP to Modbus RTU protocol conversionMODGTWYTM, Set Modbus gateway command storage time and automatic query intervalMODCMDEDIT, Modbus configuration gateway pre-stored instruction query and editingHTPREQMODE, Query/Set HTTP Request MethodHTPURL, Query/Set HTTP URL PathHTPHEAD, Query/Set HTTP headerMQTTCLOUD, Query/Set MQTT Target PlatformMQTKPALIVE, Query/Set MQTT Keep-Alive Heartbeat Packet Sending PeriodMQTDEVID, Query/Set MQTT Device Name (Client ID)MQTUSER, Query/Set MQTT User Name (User Name/Device Name)MQTPASS, Query/set MQTT product password (MQTT password/Device Secret)MQTTPRDKEY, Query/Set the Product Key of Alibaba Cloud MQTTMQTSUB, Query/Set MQTT Subscription TopicMQTPUB, Query/Set MQTT Publishing Topic"

var _ATCommand_index = [...]uint16{0, 18, 38, 54, 73, 95, 125, 154, 208, 241, 279, 370, 404, 456, 499, 553, 598, 633, 672, 710, 781, 815, 875, 935, 1014, 1095, 1136, 1167, 1197, 1238, 1307, 1355, 1412, 1482, 1541, 1582, 1621}

func (i ATCommand) String() string {
	if i < 0 || i >= ATCommand(len(_ATCommand_index)-1) {
		return "ATCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ATCommand_name[_ATCommand_index[i]:_ATCommand_index[i+1]]
}
