// Code generated by "stringer -type=ATCmd -linecomment"; DO NOT EDIT.

package atcommands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdInvalid-0]
	_ = x[CmdModel-1]
	_ = x[CmdName-2]
	_ = x[CmdSn-3]
	_ = x[CmdReboot-4]
	_ = x[CmdRestore-5]
	_ = x[CmdVer-6]
	_ = x[CmdMac-7]
	_ = x[CmdLora-8]
	_ = x[CmdWan-9]
	_ = x[CmdLPort-10]
	_ = x[CmdSock-11]
	_ = x[CmdLinkSta-12]
	_ = x[CmdUartClr-13]
	_ = x[CmdRegMod-14]
	_ = x[CmdRegInfo-15]
	_ = x[CmdHeartMod-16]
	_ = x[CmdHeartInfo-17]
	_ = x[CmdShortM-18]
	_ = x[CmdTmoRst-19]
	_ = x[CmdTmoLink-20]
	_ = x[CmdWebCfgPort-21]
	_ = x[CmdModWkMod-22]
	_ = x[CmdModPtcl-23]
	_ = x[CmdModGtwyTm-24]
	_ = x[CmdModCmdEdit-25]
	_ = x[CmdHtpReqMode-26]
	_ = x[CmdHtpUrl-27]
	_ = x[CmdHtpHead-28]
	_ = x[CmdMqttCloud-29]
	_ = x[CmdMqtKpAlive-30]
	_ = x[CmdMqtDevId-31]
	_ = x[CmdMqtUser-32]
	_ = x[CmdMqtPass-33]
	_ = x[CmdMqtPrdKey-34]
	_ = x[CmdMqtSub-35]
	_ = x[CmdMqtPub-36]
}

const _ATCmd_name = "INVALIDMODELNAMESNREBTRESTOREVERMACLORAWANLPORTSOCKLINKSTAUARTCLRREGMODREGINFOHEARTMODHEARTINFOSHORTMTMORSTTMOLINKWEBCFGPORTMODWKMODMODPTCLMODGTWYTMMODCMDEDITHTPREQMODEHTPURLHTPHEADMQTTCLOUDMQTKPALIVEMQTDEVIDMQTUSERMQTPASSMQTTPRDKEYMQTSUBMQTPUB"

var _ATCmd_index = [...]uint8{0, 7, 12, 16, 18, 22, 29, 32, 35, 39, 42, 47, 51, 58, 65, 71, 78, 86, 95, 101, 107, 114, 124, 132, 139, 148, 158, 168, 174, 181, 190, 200, 208, 215, 222, 232, 238, 244}

func (i ATCmd) String() string {
	if i < 0 || i >= ATCmd(len(_ATCmd_index)-1) {
		return "ATCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ATCmd_name[_ATCmd_index[i]:_ATCmd_index[i+1]]
}
